# Generated by Django 3.2.12 on 2022-03-08 21:10

import apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(blank=True, max_length=48)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('img_profile', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.rename_img, verbose_name='photo de profile')),
                ('img_bg', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.rename_img, verbose_name='photo de couverture')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('adress', models.CharField(blank=True, max_length=128, verbose_name='adress')),
                ('town', models.CharField(blank=True, max_length=68, verbose_name='town')),
                ('zipcode', models.CharField(blank=True, max_length=22, verbose_name='zipcode')),
                ('country', models.CharField(blank=True, max_length=45, verbose_name='country')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('link_linkedin', models.URLField(blank=True, verbose_name='linkedin profile link')),
                ('link_gitthub', models.URLField(blank=True, verbose_name='gitthub profile link')),
                ('link_twitter', models.URLField(blank=True, verbose_name='twitter profile link')),
                ('link_mysite', models.URLField(blank=True, verbose_name='mysite link')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
